version: "3"
services:
    pg-tasks:
        container_name: pg-hexagonal
        image: postgres:12.3
        ports:
            - 5432:5432
        environment: 
            - POSTGRES_DB=hexagonal
            - POSTGRES_PASSWORD=12345678
            - POSTGRES_HOST_AUTH_METHOD=trust
